#12.12.22 Reviewed Homework
# 12.13.22 Reviewing All lessons/notes

'''
Data types
Intiger = 1
float = 100.04
string = "1" 


Variable = A symbolic name that is reference or pointer to an object. 
name = "Leo"
Object = A collection of data (Variables) & methods (Functions) that act on those dada.

Object vs Class = Object is a real world entity such as pen, laptop, mobile, bed, keyboard, mouse, chair etc. 
Class is a group of similar objects.
An object is an Instance of a class

String 





'''

#Homework Home Teams (2)

#Olivia = Team A (Rock, Paper Scissors)
#1 File - Collect player names
# save players score
#    best if 3/5/7 - win 1 point per round(Score is the sum of all won rounds / player)
#    gotcha: what to do with Ties
#Use Classes where possible
#Make sure output is clean
#Use loops
#Free to use more of the tools we have learned

#Livier = Team B (Rock, Paper Scissors)
#1 File - Collect player names
# save players score
#    best if 3/5/7 - win 1 point per round(Score is the sum of all won rounds / player)
#    gotcha: what to do with Ties
#Use Classes where possible
#Make sure output is clean
#Use loops
#Free to use more of the tools we have learned


